#ifndef _TO_CORE_REQUEST_PACKAGE_INFO_H_
#define _TO_CORE_REQUEST_PACKAGE_INFO_H_

typedef enum TOReqPackageType {
    TO_CLIENT_CONNECTION_REQUEST_PACKAGE,

    TO_GET_SELF_ENTITY_REQUEST_PACKAGE,

    TO_USE_REQUEST_PACKAGE

    /*
    TO_CHARACTER_POSITION_UPDATE_REQUEST_PACKAGE,
    TO_CHARACTER_INFO_REQUEST_PACKAGE,

    TO_TILE_INFO_REQUEST_PACKAGE,

    TO_NEAR_CREATURES_COUNT_REQUEST_PACKAGE,
    TO_NEAR_CREATURES_INFO_REQUEST_PACKAGE
    */
} TOReqPackageType;

typedef struct TOReqPackageInfo {
    TOReqPackageType type;
    int success;
} TOReqPackageInfo;

#endif